name: e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      # Existing functionality to assit with git steps
        uses: actions/checkout@v4
      - name: Cypress run
      # This actually assits with installing npm
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          spec: cypress/e2e/github_actions.cy.ts